# Generated by Django 4.2.4 on 2023-08-21 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CAFFOOD', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='course',
            new_name='food',
        ),
    ]
