# Generated by Django 4.2.4 on 2023-08-25 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAFFOOD', '0002_rename_course_orderitem_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='code',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
