# Generated by Django 4.2.4 on 2023-08-25 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CAFFOOD', '0003_order_code_order_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='code',
        ),
    ]
